apiVersion: apps/v1
kind: Deployment
metadata:
  name: premium-llama-13b
  namespace: infer
  labels:
    inferno.server.managed: "true"
    inferno.server.name: vllm-001
    inferno.server.model: llama_13b
    inferno.server.class: Premium
    inferno.server.allocation.accelerator: MI250
    inferno.server.allocation.maxbatchsize: "8"
    inferno.server.load.rpm: "30"
    inferno.server.load.numtokens: "2048"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: main
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
